service:
  name: patchat

provider:
  name: aws
  runtime: nodejs12.x
  websocketsApiName: patchat-api
  websocketsApiRouteSelectionExpression: $request.body.action
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    CONN_TABLE: ${self:custom.tableNames.connections}
    MSG_TABLE: ${self:custom.tableNames.messages}

plugins:
  - serverless-iam-roles-per-function

package:
  individually: true

custom:
  tableNames:
    connections: patchat-connections
    messages: patchat-messages

functions:
  ConnectHandler:
    handler: connect.handler
    memorySize: 128
    events:
      - websocket: $connect
    package:
      artifact: dist/packages/connect.zip
    iamRoleStatements:
      - Effect: Allow
        Action:
          - execute-api:ManageConnections
        Resource:
          - arn:aws:execute-api:*:*:*/@connections/*
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - Fn::GetAtt:
              - ConnectionsTable
              - Arn
  DisconnectHandler:
    handler: disconnect.handler
    memorySize: 128
    events:
      - websocket: $disconnect
    package:
      artifact: dist/packages/disconnect.zip
    iamRoleStatements:
      - Effect: Allow
        Action:
          - execute-api:ManageConnections
        Resource:
          - arn:aws:execute-api:*:*:*/@connections/*
      - Effect: Allow
        Action: 
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt:
              - ConnectionsTable
              - Arn
  MessageHandler:
    handler: sendmessage.handler
    memorySize: 128
    events:
      - websocket:
          route: sendmessage
    package:
      artifact: dist/packages/sendmessage.zip
    iamRoleStatements:
      - Effect: Allow
        Action:
          - execute-api:ManageConnections
        Resource:
          - arn:aws:execute-api:*:*:*/@connections/*
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - Fn::GetAtt:
              - MessagesTable
              - Arn
      - Effect: Allow
        Action:
          - dynamodb:Query
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt:
              - ConnectionsTable
              - Arn
          - Fn::Join:
              - /
              - 
                - Fn::GetAtt:
                    - ConnectionsTable
                    - Arn
                - index/*
  GetMessagesHandler:
    handler: getmessages.handler
    memorySize: 128
    events:
      - websocket:
          route: getmessages
    package:
      artifact: dist/packages/getmessages.zip
    iamRoleStatements:
      - Effect: Allow
        Action:
          - execute-api:ManageConnections
        Resource:
          - arn:aws:execute-api:*:*:*/@connections/*
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - Fn::GetAtt:
              - MessagesTable
              - Arn
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource:
          - Fn::GetAtt:
              - ConnectionsTable
              - Arn

resources:
  Resources:
    ConnectionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNames.connections}
        AttributeDefinitions:
          - AttributeName: connectionId
            AttributeType: S
          - AttributeName: siteId
            AttributeType: S
        KeySchema:
          - AttributeName: connectionId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: siteIndex
            KeySchema:
              - AttributeName: siteId
                KeyType: HASH
            Projection:
              ProjectionType: KEYS_ONLY
        BillingMode: PAY_PER_REQUEST
    MessagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableNames.messages}
        AttributeDefinitions:
          - AttributeName: siteId
            AttributeType: S
          - AttributeName: msgTimestamp
            AttributeType: N
        KeySchema:
          - AttributeName: siteId
            KeyType: HASH
          - AttributeName: msgTimestamp
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST